spring:
  application:
    name: discovery-server

server:
  port: 9090

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    fetch-registry: false
    register-with-eureka: false