spring:
  application:
    name: currency-conversion-service
  zipkin:
    sender:
      type: web

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/


